//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluelightConferenceCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConferenceRoom
    {
        public int ConferenceRoomID { get; set; }
        public string ConferenceRoomCode { get; set; }
        public string Description { get; set; }
        public int RoomTypeID { get; set; }
        public int Capacity { get; set; }
    
        public virtual RoomType RoomType { get; set; }
    }
}
